root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/cmd/api"
  cmd = "go build -o ./tmp/cmd/api ./cmd/api/main.go"
  args_bin = []
  full_bin = "APP_ENV=dev APP_USER=air ./tmp/cmd/api"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "docker", "bin", "client"]
  include_dir = []
  exclude_file = []
  exclude_regex = ["_test.go"]
  delay = 1000
  kill_delay = "0s"
  stop_on_error = true
  log = "air_errors.log"
  send_interrupt = false

[log]
  time = false

[color]
  app = ""
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
