version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    networks:
      - postgres-network
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${POSTGRES_DB:-zoomer}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456789}

  redis:
		image: redis:7.0-alpine
		container_name: redis
		ports:
			- "6379:6379"
		networks:
			- redis-network
		volumes:
			- ./.docker/redis/data:/data
		restart: always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - minio-network
    volumes:
      # - ./storage:/data
      - ./.docker/minio:/var/lib/minio
    command: server --console-address ":9001" /var/lib/minio
    restart: always

  rabbitmq:
    image: rabbitmq:3.11.3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ./.docker/rabbitmq/data:/var/lib/rabbitmq
      - ./.docker/rabbitmq/log:/var/log/rabbitmq
    restart: always
    networks:
      - rabbitmq-network

  app:
    image: zoomer
    container_name: zoomer
    # platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      # dockerfile: ../build/Dockerfile.dev.air
			args:
				- APP_PATH=./cmd
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
			- redis
      - minio
      - rabbitmq
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    # working_dir: /app/cmd
    restart: always

  # nginx:
  #   image: nginx:1.21.6-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf/default.conf
  #   depends_on:
  #     - app
  #   networks:
  #     - nginx-network

networks:
  # nginx-network:
  #   driver: bridge
  postgres-network:
    driver: bridge
  minio-network:
    driver: bridge
  rabbitmq-network:
    driver: bridge
	redis-network:
		driver: bridge

# https://github.dev/NooBeeID/simple-go-search/tree/develop
