version: "3.7"

services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

      # - POSTGRES_DB=${POSTGRES_DB:-todos}
      # - POSTGRES_USER=${POSTGRES_USER:-postgres}
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password1}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    image: zoomer
    container_name: zoomer
    build: ./
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure
