version: "3.9"

services:
  postgres:
    environment:
      POSTGRES_HOST: postgres
      # - POSTGRES_HOST_AUTH_METHOD=trust
      # POSTGRES_DB: zoomer
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: 123456789

  redis-master:
    environment:
      - REDIS_HOST=redis-master
    command: redis-server --requirepass master_password

  redis-slave:
    command: redis-server --slaveof redis-master 6379 --masterauth master_password --requirepass slave_password

  redis-sentinel:
    environment:
      - REDIS_MASTER_HOST=redis-master
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf

  minio:
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /var/lib/minio

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RMQ_VHOST}

  app:
    build:
      context: .
      target: development
      args:
        TARGET: development
