version: "3.9"

services:
  postgres:
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=123456789
      - PG_DB=zoomer
      # - POSTGRES_HOST_AUTH_METHOD=trust

  # minio:
  #   environment:
  #     MINIO_ENDPOINT: localhost:9000

  rabbitmq:
    environment:
      # - RABBITMQ_DEFAULT_USER=guest
      # - RABBITMQ_DEFAULT_PASS=guest
      # - RABBITMQ_DEFAULT_VHOST=zoomer
      - RMQ_HOST=rabbitmq

  app:
    build:
      context: .
      target: development
      args:
        TARGET: development
    command: ["make", "run"]
