version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    networks:
      - postgres-network
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${POSTGRES_DB:-zoomer}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456789}

  redis-master:
    image: redis:7.0-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - ./.docker/redis/data/master:/data
    command: redis-server --appendonly yes
    restart: always

  redis-slave:
    image: redis:7.0-alpine
    container_name: redis-slave
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --slaveof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - redis-network
    volumes:
      - ./.docker/redis/data/slave:/data
    restart: always

  redis-sentinel:
    image: redis:7.0-alpine
    container_name: redis-sentinel
    ports:
      - "26379:26379"
    command: redis-sentinel /etc/redis/sentinel.conf
    # command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave
    networks:
      - redis-network
    volumes:
      - ./.docker/redis/sentinel:/etc/redis
      - ./.docker/redis/config/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    restart: always

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "6381:6381"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - minio-network
    volumes:
      # - ./.docker/minio:/var/lib/minio
      - ./.docker/minio/data:/data
      - ./.docker/minio/config:/root/.minio
    command: server --console-address ":9001" /var/lib/minio
    restart: always

  rabbitmq:
    image: rabbitmq:3.11.3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ./.docker/rabbitmq/data:/var/lib/rabbitmq
      - ./.docker/rabbitmq/log:/var/log/rabbitmq
    restart: always
    networks:
      - rabbitmq-network

  app:
    image: thuongtruong1009/zoomer
    # platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      # dockerfile: ../build/Dockerfile.dev.air
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8081:8080"
    depends_on:
      - postgres
      - redis-master
      - minio
      - rabbitmq
    volumes:
      - .:/app
      # - $GOPATH/pkg/mod:/go/pkg/mod
    # working_dir: /app/cmd
    networks:
      - postgres-network
      - minio-network
      - rabbitmq-network
      - redis-network
    restart: always

  # app2:
  #   <<: *app

  # nginx:
  #   image: nginx:1.23.3-alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  # environment:
  #   - NGINX_HOST=127.0.01,localhost,0.0.0.0
  #   - NGINX_PORT=80
  #   - APP_HOST_1=app
  #   - APP_HOST_2=app2
  #   - APP_PORT=${APP_PORT}
  #   volumes:
  #     - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - app
  # - app2
  #   networks:
  #     - nginx-network
  #   restart: always

networks:
  # nginx-network:
  #   driver: bridge
  postgres-network:
    driver: bridge
  minio-network:
    driver: bridge
  rabbitmq-network:
    driver: bridge
  redis-network:
    driver: bridge
# https://github.dev/NooBeeID/simple-go-search/tree/develop
