version: "3.9"

services:
  postgres:
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_PORT: 5432
      # - POSTGRES_HOST_AUTH_METHOD=trust

  minio:
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS: oo8xvrXe90ysYFKq
      MINIO_SECRET: wJU2cLdHICXPI8VKj5OfWKwCcn0MTEsy
      MINIO_ENDPOINT: localhost:9000

  rabbitmq:
    environment:
      # - RABBITMQ_DEFAULT_USER=guest
      # - RABBITMQ_DEFAULT_PASS=guest
      # - RABBITMQ_DEFAULT_VHOST=zoomer
      RMQ_URI: amqp://guest:guest@localhost:5672/zoomer

  app:
    build:
      context: .
      target: development
      args:
        TARGET: development
