version: "3.7"

services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: 123456789
      # POSTGRES_DB: zoomer

      - POSTGRES_DB=${POSTGRES_DB:-zoomer}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456789}
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: zoomer
    container_name: zoomer
    # platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      # dockerfile: ../build/Dockerfile.dev.air
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    command: sh docker-entrypoint.dev.sh
    # working_dir: /app/cmd
    # command: reflex -r '(\.go$$|go\.mod)' -s go run .
    restart: on-failure
