---
apiVersion: apps/v1
kind: Deployment # Type of Kubernetes resource
metadata:
  name: zoomer # Name of the Kubernetes resource
spec:
  type: NodePort # A port is opened on each node in your cluster via Kube proxy.
  ports: # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
    - name: http
      port: 9090
      targetPort: 8080
  replicas: 3 # Number of pods to run at any given time
  selector:
    app: zoomer # This deployment applies to any Pods matching the specified label
  template: # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels: # The labels that will be applied to all of the pods in this deployment
        app: zoomer
    spec: # Spec for the container which will run in the Pod
      containers:
        - name: zoomer
          image: gcr.io/thuongtruong1009/zoomer:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # Should match the port number that the Go application listens on
					env:
            - name: POSTGRES_DB
							value: "-postgres"
          livenessProbe: # To check the health of the Pod
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe: # To check if the Pod is ready to serve traffic or not
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
