apiVersion: v1
kind: Service
metadata:
  name: zoomer
spec:
  type: NodePort
  selector:
    app: zoomer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
		- name: websocket
			port: 8081
			targetPort: 8081
			protocol: TCP
