name: golangci-lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - "!cmd/**"
      - "!configs/**"
      - "!db/**"
      - "!internal/**"
      - "!utils/**"
  pull_request:
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17"
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

          args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          skip-cache: true

          skip-pkg-cache: true

          skip-build-cache: true
