name: golangci-lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - "!cmd/**"
      - "!configs/**"
      - "!db/**"
      - "!internal/**"
      - "!utils/**"
			- "!lib/**"
			- "!validators/**"
  pull_request:
    paths-ignore:
      - "!cmd/**"
      - "!configs/**"
      - "!db/**"
      - "!internal/**"
      - "!utils/**"
			- "!lib/**"
			- "!validators/**"
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          stable: "false"
          go-version: "1.20"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          args: --issues-exit-code=0
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.29.0
          golangci-lint run --issues-exit-code=0
